const products = [
  { n: '01', title: 'Praticáveis', tag: 'Locação', image: '/images/runway.jpeg', text: 'Palcos, tablados e passarelas modulares para qualquer formato de evento.' },
  { n: '02', title: 'Gradis', tag: 'Locação + venda', image: '/images/gradil-industrial.jpeg', text: 'Controle de público, isolamento de áreas e segurança com instalação ágil.' },
  { n: '03', title: 'Box trusses', tag: 'Locação', image: '/images/stage-corporate.jpeg', text: 'Estruturas para som, luz, comunicação visual, cenografia e bares.' },
  { n: '04', title: 'Fechamentos', tag: 'Locação', image: '/images/fabric.jpeg', text: 'Tecido e soluções de acabamento para delimitar espaços com elegância.' },
];
export default function Home() {
  return <main>
    <header className="nav"><a className="brand" href="#top" aria-label="Móvel Estrutura — início"><b>MÓVEL</b><span>ESTRUTURA</span></a><nav aria-label="Navegação principal"><a href="#solucoes">Soluções</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a></nav><a className="pill" href="mailto:movelestrutura@gmail.com?subject=Orçamento%20Móvel%20Estrutura">Pedir orçamento <span>↗</span></a></header>
    <section className="hero" id="top"><img src="/images/stage-corporate.jpeg" alt="Palco modular instalado pela Móvel Estrutura em evento corporativo"/><div className="heroShade"/><p className="eyebrow">BELO HORIZONTE · MG <i/> LOCAÇÃO &amp; VENDA</p><div className="heroCopy"><h1>Estrutura que<br/><em>move</em> seu evento.</h1><p>Do primeiro encaixe ao público chegando. Soluções modulares, seguras e prontas para transformar espaços.</p><a className="cta" href="#solucoes">Explore as soluções <span>↓</span></a></div><div className="heroIndex"><span>01</span><div><b>PRATICÁVEIS</b><small>Palcos · passarelas · tablados</small></div></div></section>
    <section className="statement" id="sobre"><p className="kicker">[ O QUE NOS MOVE ]</p><h2>Seu evento não pode parar.<br/>Nossa estrutura também não.</h2><div className="statementGrid"><p>A Móvel Estrutura é especialista em soluções práticas, seguras e versáteis para eventos corporativos, sociais, feiras e shows.</p><p>Da locação à venda, entregamos o material certo, no tempo certo — com qualidade, segurança e pontualidade.</p></div></section>
    <section className="products" id="solucoes"><div className="sectionHead"><p className="kicker">[ SOLUÇÕES ]</p><h2>Materiais que<br/>fazem acontecer.</h2><p>Estruturas modulares para criar, organizar, proteger e transformar.</p></div><div className="productList">{products.map((p)=><article className="product" key={p.n}><div className="productMeta"><span>{p.n}</span><span>{p.tag}</span></div><img src={p.image} alt={`${p.title} instalado pela Móvel Estrutura`}/><div className="productCopy"><h3>{p.title}</h3><p>{p.text}</p><a href={`mailto:movelestrutura@gmail.com?subject=Orçamento%20de%20${encodeURIComponent(p.title)}`}>Consultar <span>↗</span></a></div></article>)}</div></section>
    <section className="projects" id="projetos"><div className="projectIntro"><p className="kicker">[ EM CAMPO ]</p><h2>Montado.<br/>Entregue.<br/><em>Pronto.</em></h2></div><div className="mosaic"><figure className="wide"><img src="/images/runway.jpeg" alt="Passarela modular em auditório"/><figcaption>Passarela modular <span>BH · MG</span></figcaption></figure><figure><img src="/images/tiers.jpeg" alt="Praticáveis em níveis para evento"/><figcaption>Estrutura em níveis</figcaption></figure><figure><img src="/images/gradil-mall.jpeg" alt="Gradil articulado em shopping"/><figcaption>Controle de acesso</figcaption></figure><figure className="wide"><img src="/images/led-stage.jpeg" alt="Palco com painel de LED"/><figcaption>Palco corporativo <span>Montagem modular</span></figcaption></figure></div></section>
    <section className="process"><p className="kicker">[ SIMPLES ASSIM ]</p><h2>Da demanda à entrega.</h2><ol><li><b>01</b><span>Conte seu projeto</span><p>Evento, data, local e o que você precisa.</p></li><li><b>02</b><span>Receba a solução</span><p>Dimensionamos materiais e logística.</p></li><li><b>03</b><span>Faça acontecer</span><p>Entregamos com segurança e pontualidade.</p></li></ol></section>
    <section className="contact"><p className="kicker">[ VAMOS MONTAR? ]</p><h2>A estrutura certa<br/>começa com uma <em>conversa.</em></h2><a className="contactButton" href="mailto:movelestrutura@gmail.com?subject=Solicitação%20de%20orçamento">Solicitar orçamento <span>↗</span></a></section>
    <footer><a className="brand" href="#top"><b>MÓVEL</b><span>ESTRUTURA</span></a><p>Belo Horizonte · Minas Gerais</p><div><a href="mailto:movelestrutura@gmail.com">movelestrutura@gmail.com</a><a href="https://www.instagram.com/movelestrutura/" target="_blank" rel="noreferrer">Instagram ↗</a></div></footer>
  </main>;
}
