'use client';
import { useEffect, useRef, useState } from 'react';
const products = [
  { n: '01', title: 'Praticáveis', tag: 'Locação', image: '/images/runway.jpeg', text: 'Locação de praticáveis modulares para palcos, tablados, passarelas e desfiles em eventos de todos os portes.' },
  { n: '02', title: 'Gradis', tag: 'Locação + venda', image: '/images/gradil-product.jpeg', text: 'Gradis para locação e venda, ideais para controle de público, isolamento de áreas e organização segura de eventos.' },
  { n: '03', title: 'Box truss', tag: 'Locação', image: '/images/box-truss.jpeg', text: 'Box truss para estruturas de som, iluminação, comunicação visual, cenografia e montagem de bares para eventos.' },
  { n: '04', title: 'Fechamentos', tag: 'Locação', image: '/images/fechamento-tecido.jpeg', text: 'Fechamento em tecido para delimitar ambientes, ocultar áreas técnicas e criar acabamento visual em eventos.' },
];
export default function Home() {
  const heroRef = useRef<HTMLElement>(null);
  const [progress, setProgress] = useState(0);
  useEffect(() => {
    let frame = 0;
    const update = () => { cancelAnimationFrame(frame); frame = requestAnimationFrame(() => { const el = heroRef.current; if (!el) return; const max = Math.max(el.offsetHeight - innerHeight, 1); setProgress(Math.min(1, Math.max(0, -el.getBoundingClientRect().top / max))); }); };
    update(); addEventListener('scroll', update, { passive: true }); addEventListener('resize', update);
    return () => { cancelAnimationFrame(frame); removeEventListener('scroll', update); removeEventListener('resize', update); };
  }, []);
  return <main>
    <header className="nav"><a className="brand" href="#top" aria-label="Móvel Estrutura — início"><b>MÓVEL</b><span>ESTRUTURA</span></a><nav aria-label="Navegação principal"><a href="#solucoes">Soluções</a><a href="#projetos">Projetos</a><a href="#sobre">Sobre</a></nav><a className="pill" href="mailto:movelestrutura@gmail.com?subject=Orçamento%20Móvel%20Estrutura">Pedir orçamento <span>↗</span></a></header>
    <section className="hero" id="top" ref={heroRef}><div className="heroScene"><img className="heroBack" src="/images/stage-corporate.jpeg" alt="Estrutura para evento corporativo montada em Belo Horizonte"/><div className="heroShade"/><div className="panelReveal" style={{clipPath:`inset(${100-Math.min(1,progress*1.45)*100}% 0 0)`}}><img src="/images/stage-corporate.jpeg" alt="Palco modular e painel de lona para evento corporativo"/></div><div className="heroCopy" style={{opacity:Math.max(0,(progress-.48)/.3),transform:`translateY(${Math.max(0,1-(progress-.48)/.3)*70}px)`}}><p className="eyebrow">LOCAÇÃO &amp; VENDA</p><h1>Estrutura que<br/><em>move</em> seu evento.</h1><p>Locação e venda de estruturas para eventos em Belo Horizonte: praticáveis, gradis, box truss e fechamentos com montagem segura e entrega pontual.</p><a className="cta" href="#solucoes">Explore as soluções <span>↓</span></a></div><span className="scrollCue" style={{opacity:1-Math.min(1,progress*3)}}>Role para revelar <b>↓</b></span></div></section>
    <section className="statement" id="sobre"><p className="kicker">[ ESTRUTURAS PARA EVENTOS EM BH ]</p><h2>Seu evento não pode parar.<br/>Nossa estrutura também não.</h2><div className="statementGrid"><p>A Móvel Estrutura é uma empresa de Belo Horizonte especializada em locação e venda de estruturas para eventos corporativos, sociais, feiras, shows e desfiles.</p><p>Atendemos produtores, agências, empresas e organizadores em Minas Gerais com materiais versáteis, montagem segura, logística eficiente e pontualidade.</p></div></section>
    <section className="products" id="solucoes"><div className="sectionHead"><p className="kicker">[ LOCAÇÃO E VENDA ]</p><h2>Estruturas para<br/>fazer acontecer.</h2><p>Soluções modulares para montar palcos, organizar públicos, delimitar ambientes e transformar espaços de eventos.</p></div><div className="productList">{products.map((p)=><article className={`product product-${p.n}`} key={p.n}><div className="productMeta"><span>{p.n}</span><span>{p.tag}</span></div><img src={p.image} alt={`${p.title} para eventos fornecido pela Móvel Estrutura em Belo Horizonte`}/><div className="productCopy"><h3>{p.title}</h3><p>{p.text}</p><a href={`mailto:movelestrutura@gmail.com?subject=Orçamento%20de%20${encodeURIComponent(p.title)}`}>Consultar <span>↗</span></a></div></article>)}</div></section>
    <section className="projects" id="projetos"><div className="projectIntro"><p className="kicker">[ EM CAMPO ]</p><h2>Montado.<br/>Entregue.<br/><em>Pronto.</em></h2></div><div className="mosaic"><figure className="wide"><img src="/images/runway.jpeg" alt="Passarela modular em auditório"/><figcaption>Passarela modular <span>BH · MG</span></figcaption></figure><figure><img src="/images/tiers.jpeg" alt="Praticáveis em níveis para evento"/><figcaption>Estrutura em níveis</figcaption></figure><figure><img src="/images/gradil-mall.jpeg" alt="Gradil articulado em shopping"/><figcaption>Controle de acesso</figcaption></figure><figure className="wide"><img src="/images/led-stage.jpeg" alt="Palco com painel de LED"/><figcaption>Palco corporativo <span>Montagem modular</span></figcaption></figure></div></section>
    <section className="process"><p className="kicker">[ SIMPLES ASSIM ]</p><h2>Da demanda à entrega.</h2><ol><li><b>01</b><span>Conte seu projeto</span><p>Evento, data, local e o que você precisa.</p></li><li><b>02</b><span>Receba a solução</span><p>Dimensionamos materiais e logística.</p></li><li><b>03</b><span>Faça acontecer</span><p>Entregamos com segurança e pontualidade.</p></li></ol></section>
    <section className="contact"><p className="kicker">[ ORÇAMENTO PARA SEU EVENTO ]</p><h2>A estrutura certa<br/>começa com uma <em>conversa.</em></h2><p className="contactLead">Conte a data, o local e o formato do evento. Nossa equipe indica os materiais adequados e prepara uma proposta personalizada.</p><a className="contactButton" href="mailto:movelestrutura@gmail.com?subject=Solicitação%20de%20orçamento"><small>Fale com a equipe</small><strong>Solicitar<br/>orçamento</strong><span>↗</span></a></section>
    <footer><a className="brand" href="#top"><b>MÓVEL</b><span>ESTRUTURA</span></a><p>Belo Horizonte · Minas Gerais</p><div><a href="mailto:movelestrutura@gmail.com">movelestrutura@gmail.com</a><a href="https://www.instagram.com/movelestrutura/" target="_blank" rel="noreferrer">Instagram ↗</a></div></footer>
  </main>;
}
